from django.urls import path
from . import views

urlpatterns = [
    path('',views.Home_page,name='home'),
    path('register/',views.Register_page,name='register'),
    path('login/',views.Login_page,name='login'),
    path('logout/',views.Logout_page,name='logout'),
    path('api/register/', views.register_api, name='api_register'),
    path('api/login/', views.login_api, name='api_login'),
    path('api/refresh/', views.refresh_token_api),
    path('api/logout/', views.logout_api),
    path('about/',views.About_page,name='about'),
    path('update/<int:id>/',views.Profile_update,name='update'),
    path('service/',views.Service_page,name='service'),
    path('favorites/', views.favorite_list, name='favorites'),
    path('favorites/add/<int:product_id>/', views.add_to_favorite, name='add_to_favorite'),
    path('toggle-favorite/<int:product_id>/', views.toggle_favorite, name='toggle_favorite'),
    path('favorites/remove/<int:product_id>/', views.remove_from_favorite, name='remove_from_favorite'),
    path('catagory/',views.Catagory_page,name='catagory'),
    path('contact/',views.Contact_page,name='contact'),
    path('products/<int:id>/', views.product_detail, name='product_detail'),
    # path('product/<str:name>/',views.Product_page,name='product'),
    path('product/<slug:name>/', views.Product_page, name='product'),
    path('cart/', views.cart_view, name='cart'),
    path('add-to-cart/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('cart/remove/<int:cart_item_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('cart/update/<int:cart_item_id>/', views.update_cart, name='update_cart_quantity'),
    path('checkout/', views.checkout, name='checkout'),
    path('orders/', views.OrderListView.as_view(), name='order_list'),
    path('create-stripe-session/<uuid:order_id>/', views.create_stripe_session, name='create_stripe_session'),
    path('success/<uuid:order_id>/', views.payment_success, name='payment_success'),
    path('cancel/<uuid:order_id>/', views.payment_cancel, name='payment_cancel'),
    path('search-suggestions/', views.search_suggestions, name='search_suggestions'),
]