# Generated by Django 5.1.3 on 2026-03-02 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0009_order_orderitem_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='stripe_session_id',
            new_name='stripe_payment_intent',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.FloatField(),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
